
# docker-compose.yml

version: "3.2"
services:

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  server:
    build: ./server
    tty: true
    ports:
      - "4001:4001"
    volumes:
      - './server:/server'
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache

  frontend:
    build: ./frontend
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/frontend'
    links:
      - server


# Host volumes used to store code.
volumes:
  server:
  frontend: